const projectsData = [
  {
    name: "dbv-minority-report",
    title_es: "DBV Minority Report",
    title_en: "DBV Minority Report",
    description_es: "Interfaz médica touchless inspirada en 'Minority Report'. Carga local, visualización 3D y manipulación gestual de radiografías o cualquier imagen con webcam utilizando Three.js y MediaPipe.",
    description_en: "Touchless medical interface inspired by 'Minority Report'. Local loading, 3D visualization, and gestural manipulation of X-rays or any image with a webcam using Three.js and MediaPipe.",
    category: "ai",
    lang: "JavaScript",
    stars: 0,
    github: "https://github.com/davidbuenov/dbv-minority-report",
    demo: null,
    tags: ["Three.js", "MediaPipe", "Computer Vision", "Webcam", "Medical UI"],
    date: "2026-05-24T16:51:50Z"
  },
  {
    name: "dbv-voice-transcrypt",
    title_es: "DBV VoiceTranscrypt",
    title_en: "DBV VoiceTranscrypt",
    description_es: "Herramienta profesional de transcripción y análisis de audio híbrida. Utiliza Whisper en local (con soporte GPU) y análisis inteligente mediante Gemini o Gemma 4 en local. Privacidad total.",
    description_en: "Professional hybrid audio transcription and analysis tool. Uses local Whisper (with GPU support) and intelligent analysis via Gemini or local Gemma 4. Complete privacy.",
    category: "ai",
    lang: "Python",
    stars: 2,
    github: "https://github.com/davidbuenov/dbv-voice-transcrypt",
    demo: null,
    tags: ["Whisper", "Gemini API", "Gemma 4", "Audio Transcription", "Local AI"],
    date: "2026-05-05T18:13:31Z"
  },
  {
    name: "unreal-smart-cleaner",
    title_es: "Unreal Smart Cleaner",
    title_en: "Unreal Smart Cleaner",
    description_es: "Utilidad diseñada para desarrolladores de Unreal Engine. Elimina directorios temporales pesados de proyectos inactivos, liberando gigabytes de espacio en disco sin dañar los assets principales.",
    description_en: "Utility designed for Unreal Engine developers. Cleans up heavy temporary directories from inactive projects, freeing gigabytes of disk space without damaging main assets.",
    category: "unreal",
    lang: "Python",
    stars: 6,
    github: "https://github.com/davidbuenov/unreal-smart-cleaner",
    demo: null,
    tags: ["Unreal Engine", "Python", "Disk Utility", "Developer Tools"],
    date: "2023-12-16T22:26:28Z"
  },
  {
    name: "CombinarCorrespondencia",
    title_es: "Combinar Correspondencia",
    title_en: "Word Mail Merge Utility",
    description_es: "Macro avanzada para Microsoft Word y Excel. Automatiza la combinación de correspondencia generando PDFs independientes, aplicando firmas digitales y enviándolos de forma personalizada por email.",
    description_en: "Advanced macro for Microsoft Word and Excel. Automates mail merges, generating separate PDFs, applying digital signatures, and emailing them in a customized way.",
    category: "tools",
    lang: "VBA",
    stars: 30,
    github: "https://github.com/davidbuenov/CombinarCorrespondencia",
    demo: null,
    tags: ["Microsoft Word", "VBA Macros", "Office Automation", "PDF Signing"],
    date: "2020-11-19T21:49:19Z"
  },
  {
    name: "VRGK-Community-Project-UE5",
    title_es: "VRGK Community Project UE5",
    title_en: "VRGK Community Project UE5",
    description_es: "Proyecto compilado y optimizado del framework de realidad virtual VRGK para Unreal Engine 5.3. Testeado y completamente funcional para dispositivos autónomos como Meta Quest 3.",
    description_en: "Compiled and optimized project of the VRGK virtual reality framework for Unreal Engine 5.3. Tested and fully functional for standalone devices like Meta Quest 3.",
    category: "unreal",
    lang: "C++",
    stars: 12,
    github: "https://github.com/davidbuenov/VRGK-Community-Project-UE5",
    demo: null,
    tags: ["Unreal Engine 5", "VR", "Meta Quest 3", "C++", "Virtual Reality"],
    date: "2024-01-05T19:14:15Z"
  },
  {
    name: "dbv-specs-ops",
    title_es: "DBV Specs Ops",
    title_en: "DBV Specs Ops",
    description_es: "El blueprint / marco de trabajo disciplinado que transforma a cualquier asistente de inteligencia artificial en un Ingeniero de Software Senior estructurado y eficiente.",
    description_en: "The blueprint / disciplined workflow framework that turns any AI assistant into a structured and efficient Senior Software Engineer.",
    category: "ai",
    lang: "Markdown",
    stars: 6,
    github: "https://github.com/davidbuenov/dbv-specs-ops",
    demo: null,
    tags: ["AI Engineering", "Software Architecture", "Prompts", "System Design"],
    date: "2026-04-26T21:52:45Z"
  },
  {
    name: "eer-studio",
    title_es: "EER Studio",
    title_en: "EER Studio",
    description_es: "Entorno interactivo web que permite diseñar diagramas Entidad-Relación Extendidos (EER) siguiendo de manera estricta la notación clásica de Chen.",
    description_en: "Web-based interactive environment to design Extended Entity-Relationship (EER) diagrams strictly following the classic Chen notation.",
    category: "tools",
    lang: "TypeScript",
    stars: 0,
    github: "https://github.com/davidbuenov/eer-studio",
    demo: null,
    tags: ["TypeScript", "Chen Notation", "Entity-Relationship", "Databases", "Web App"],
    date: "2025-11-30T19:27:09Z"
  },
  {
    name: "NeuroSync_Player",
    title_es: "NeuroSync Player",
    title_en: "NeuroSync Player",
    description_es: "Herramienta que permite el streaming en tiempo real de blendshapes faciales a Unreal Engine 5 mediante LiveLink, logrando animación facial directa a partir de audio de entrada.",
    description_en: "Tool that allows real-time streaming of facial blendshapes to Unreal Engine 5 using LiveLink, enabling direct facial animation from audio inputs.",
    category: "unreal",
    lang: "Python",
    stars: 0,
    github: "https://github.com/davidbuenov/NeuroSync_Player",
    demo: null,
    tags: ["Unreal Engine 5", "LiveLink", "Facial Animation", "Blendshapes", "Real-Time"],
    date: "2025-04-12T19:03:35Z"
  },
  {
    name: "ai-courses-catalog",
    title_es: "AI Courses Catalog",
    title_en: "AI Courses Catalog",
    description_es: "Aplicación web interactiva que categoriza, filtra y organiza cursos existentes de Inteligencia Artificial según su nivel de dificultad y su temática específica.",
    description_en: "Interactive web application that categorizes, filters, and organizes existing AI courses based on their difficulty level and specific topics.",
    category: "tools",
    lang: "JavaScript",
    stars: 28,
    github: "https://github.com/davidbuenov/ai-courses-catalog",
    demo: "https://davidbuenov.github.io/ai-courses-catalog/",
    tags: ["JavaScript", "Course Directory", "Artificial Intelligence", "Filter UI"],
    date: "2025-06-22T14:13:22Z"
  },
  {
    name: "ai-coding-best-practices",
    title_es: "AI Coding Best Practices",
    title_en: "AI Coding Best Practices",
    description_es: "Manuales de buenas prácticas y plantillas de prompts optimizadas para la codificación asistida por IA. Ejemplos estructurados en Python, C++, Java, SQL, C# y más.",
    description_en: "Best practice manuals and optimized prompt templates for AI-assisted coding. Structured examples in Python, C++, Java, SQL, C#, and more.",
    category: "ai",
    lang: "Mermaid",
    stars: 8,
    github: "https://github.com/davidbuenov/ai-coding-best-practices",
    demo: null,
    tags: ["AI Assistant", "Prompt Engineering", "Best Practices", "Clean Code"],
    date: "2025-10-25T14:03:26Z"
  },
  {
    name: "Unreal-universal-platform",
    title_es: "Unreal Universal Platform",
    title_en: "Unreal Universal Platform",
    description_es: "Código modular en C++ para crear plataformas móviles universales en Unreal Engine. Movimientos horizontales, verticales, rotaciones e inclinaciones físicas ideales para juegos multijugador.",
    description_en: "Modular C++ code to create universal moving platforms in Unreal Engine. Physical horizontal and vertical movements, rotations, and tilts ideal for multiplayer games.",
    category: "unreal",
    lang: "C++",
    stars: 4,
    github: "https://github.com/davidbuenov/Unreal-universal-platform",
    demo: null,
    tags: ["Unreal Engine", "C++", "Physics", "Game Dev", "Moving Platforms"],
    date: "2022-08-09T18:38:10Z"
  },
  {
    name: "dbv-pdf2deck",
    title_es: "DBV PDF to Deck",
    title_en: "DBV PDF to Deck",
    description_es: "Convertidor offline de PDFs basados en imágenes a presentaciones de PowerPoint editables. Incluye OCR local, un editor de lienzo visual y enriquecimiento opcional por IA sin subir datos a la nube.",
    description_en: "Offline image-only PDF converter to editable PowerPoint decks. Includes local OCR, a visual canvas editor, and optional AI-based text enrichment without cloud data uploads.",
    category: "ai",
    lang: "Python",
    stars: 0,
    github: "https://github.com/davidbuenov/dbv-pdf2deck",
    demo: null,
    tags: ["Python", "Local OCR", "PowerPoint", "Offline Tool", "AI Text Enrichment"],
    date: "2026-03-31T20:59:51Z"
  },
  {
    name: "dbv-agentic-edu-SQL",
    title_es: "DBV Agentic Edu SQL",
    title_en: "DBV Agentic Edu SQL",
    description_es: "Notebook de aprendizaje interactivo diseñado para introducir a desarrolladores en el funcionamiento y arquitectura de los agentes autónomos de IA utilizando SQL y bases de datos.",
    description_en: "Interactive learning notebook designed to introduce developers to the inner workings and architecture of autonomous AI agents utilizing SQL and databases.",
    category: "ai",
    lang: "Jupyter Notebook",
    stars: 4,
    github: "https://github.com/davidbuenov/dbv-agentic-edu-SQL",
    demo: null,
    tags: ["SQL", "AI Agents", "Education", "Jupyter Notebook", "Databases"],
    date: "2025-10-14T21:54:36Z"
  },
  {
    name: "dbv-nano-banana",
    title_es: "DBV Nano Banana Streamlit",
    title_en: "DBV Nano Banana Streamlit",
    description_es: "Interfaz de usuario intuitiva en Streamlit para interactuar con la potente herramienta de análisis DBV-Nano-Banana proporcionando simplemente una API key de Gemini.",
    description_en: "Intuitive Streamlit user interface to interact with the powerful DBV-Nano-Banana analysis tool by simply providing a Gemini API key.",
    category: "ai",
    lang: "Python",
    stars: 0,
    github: "https://github.com/davidbuenov/dbv-nano-banana",
    demo: null,
    tags: ["Streamlit", "Python", "Gemini API", "Nano Banana", "AI Chat"],
    date: "2025-09-14T10:39:28Z"
  },
  {
    name: "dbv-gemma4-lab",
    title_es: "DBV Gemma 4 Lab",
    title_en: "DBV Gemma 4 Lab",
    description_es: "Laboratorio y experimentos prácticos de integración local con el modelo Gemma 4 de Google, centrado en optimización de prompts y llamadas a funciones estructuradas.",
    description_en: "Practical laboratory and experiments for local integration with Google's Gemma 4 model, focusing on prompt optimization and structured function calling.",
    category: "ai",
    lang: "Python",
    stars: 4,
    github: "https://github.com/davidbuenov/dbv-gemma4-lab",
    demo: null,
    tags: ["Gemma 4", "Local LLM", "Python", "AI Labs"],
    date: "2026-04-06T15:08:03Z"
  },
  {
    name: "NeuroSync_Real-Time_API",
    title_es: "NeuroSync Real-Time API",
    title_en: "NeuroSync Real-Time API",
    description_es: "Colección de endpoints para modelos de inteligencia artificial ejecutados localmente, orientados a un sistema de audio2face en tiempo real. Prototipo educativo de aprendizaje.",
    description_en: "Collection of AI model endpoints executed locally, geared towards a real-time audio2face system. Educational learning prototype.",
    category: "ai",
    lang: "Python",
    stars: 0,
    github: "https://github.com/davidbuenov/NeuroSync_Real-Time_API",
    demo: null,
    tags: ["Audio2Face", "Deep Learning", "Endpoints", "Local API", "Python"],
    date: "2025-04-18T09:08:58Z"
  },
  {
    name: "NeuroSync_Local_API",
    title_es: "NeuroSync Local API",
    title_en: "NeuroSync Local API",
    description_es: "Código de asistencia para inferencia local de audio a animación facial, facilitando la interconexión con motores de juego mediante sockets rápidos.",
    description_en: "Helper code for local audio-to-face animation inference, facilitating fast socket interconnection with game engines.",
    category: "unreal",
    lang: "Python",
    stars: 0,
    github: "https://github.com/davidbuenov/NeuroSync_Local_API",
    demo: null,
    tags: ["Python", "Local Inference", "Animation API", "Real-Time Data"],
    date: "2025-04-12T19:04:48Z"
  },
  {
    name: "cwebp-script",
    title_es: "Cwebp Script Converter",
    title_en: "Cwebp Script Converter",
    description_es: "Scripts ligeros en lote (batch) para convertir imágenes PNG/JPG a WebP en masa, optimizando drásticamente la velocidad de carga de sitios web y portfolios.",
    description_en: "Lightweight batch scripts to mass convert PNG/JPG images to WebP, drastically optimizing website and portfolio loading speeds.",
    category: "tools",
    lang: "Batchfile",
    stars: 1,
    github: "https://github.com/davidbuenov/cwebp-script",
    demo: null,
    tags: ["Batchfile", "Image Compression", "Webp Converter", "Web Optimization"],
    date: "2022-07-04T07:36:14Z"
  },
  {
    name: "dbv-dias-festivos",
    title_es: "DBV Días Festivos",
    title_en: "DBV Holidays Utility",
    description_es: "Script en Python para parsear y obtener el calendario oficial de días festivos regionales y nacionales, exportable a formatos estructurados JSON/CSV.",
    description_en: "Python script to parse and retrieve the official calendar of regional and national holidays, exportable to structured JSON/CSV formats.",
    category: "tools",
    lang: "Python",
    stars: 2,
    github: "https://github.com/davidbuenov/dbv-dias-festivos",
    demo: null,
    tags: ["Python", "Web Scraping", "Calendar Helper", "CSV/JSON"],
    date: "2025-09-08T08:58:54Z"
  },
  {
    name: "dbv-teleprompter",
    title_es: "DBV Teleprompter",
    title_en: "DBV Teleprompter",
    description_es: "Aplicación web interactiva y ligera que actúa como un apuntador electrónico (teleprompter) personalizable, apto para PCs, móviles y tablets.",
    description_en: "Lightweight interactive web application that acts as a customizable teleprompter, suitable for PCs, mobiles, and tablets.",
    category: "tools",
    lang: "JavaScript",
    stars: 0,
    github: "https://github.com/davidbuenov/dbv-teleprompter",
    demo: null,
    tags: ["JavaScript", "Teleprompter", "Mobile Friendly", "Web Utility"],
    date: "2025-05-23T20:34:38Z"
  },
  {
    name: "tesis",
    title_es: "Tesis Doctoral",
    title_en: "PhD Doctoral Thesis",
    description_es: "Código fuente y compilado de la tesis doctoral en Ingeniería Informática defendida en la Universidad de Málaga en 2003.",
    description_en: "Source and compiled code of the PhD doctoral thesis in Computer Engineering defended at the University of Malaga in 2003.",
    category: "tools",
    lang: "TeX",
    stars: 0,
    github: "https://github.com/davidbuenov/tesis",
    demo: null,
    tags: ["LaTeX", "Research Paper", "Academic", "Computer Science PhD"],
    date: "2025-05-15T16:03:30Z"
  }
];
